- name: change DNS and NTP ILO
  hosts: [ITXILOS]
  gather_facts: no
  vars:
    ansible_network_os: ios
    dns_servers:
      - ip name-server 10.1.14.114
      - ip name-server 10.1.14.116
      - ip name-server 10.2.1.114
    ntp_servers:
      - ntp server ntpdk.root.xxx.com prefer
      - ntp server ntpus.root.xxx.com

  tasks:
    - name: "GET CONFIG"
      ios_command:
        commands:
          - "show running-config | include ip name-server"
          - "show running-config | include ntp server"
      register: get_config
    - debug: var=get_config.stdout_lines

    - name: RUN 'Remove DNS'
      when: "(get_config.stdout_lines[0][0] != '') and (item not in dns_servers)"
      with_items: "{{ get_config.stdout_lines[0] }}"
      register: remove_dns
      ios_config:
        lines:
          - "no {{ item }}"

    - name: RUN 'Set DNS'
      with_items: "{{ dns_servers }}"
      ios_config:
        lines:
          - "{{ item }}"
      register: set_dns

    - name: CHECK CHANGE - dns
      when: "(set_dns.changed == true) or (remove_dns.changed == true)"
      set_fact: configured=true

    - name: random commands
      ios_config:
        lines:
          - "clock timezone CET 1 0"
          - "clock summer-time Summer recurring last Sun Mar 3:00 last Sun Oct 4:00"
          - "ip domain-lookup"
          - "no archive"

    - name: RUN 'Remove NTP'
      when: "(get_config.stdout_lines[1][0] != '') and (item not in ntp_servers)"
      with_items: "{{ get_config.stdout_lines[1] }}"
      register: remove_ntp
      ios_config:
        lines:
          - "no {{ item }}"

    - name: RUN 'Set NTP'
      with_items: "{{ ntp_servers }}"
      ios_config:
        lines:
            - "{{ item }}"
      register: set_ntp

    - name: CHECK CHANGE - ntp
      when: "(set_ntp.changed == true) or (remove_ntp.changed == true)"
      set_fact: configured=true

    - name: RUN 'wr mem'
      when: "(configured is defined) and (configured == true)"
      register: save_config
      ios_command:
        commands:
          - "write memory"